parameters:
#    synpost_database.example.class: Synduit\SynpostDatabaseBundle\Example

services:
#    synpost_database.example:
#        class: %synpost_database.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
