<?php

namespace Synduit\SynpostDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynpostDatabaseBundle\Document\Domain;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends DocumentRepository
{
    public function createDomain($values) {
        $domain = new Domain();
        $domain->setName($values['name']);
        $this->prepareFields($domain, $values);

        $dm = $this->getDocumentManager();
        $dm->persist($domain);

        return $domain;
    }

    public function findDomain($domain_name)
    {
        return $this->findOneBy(
            array(
              'name' => $domain_name,
            )
        );
    }

    public function updateDomain($domain, $values) {
        $this->prepareFields($domain, $values);
    }

    private function prepareFields(&$domain, $values) {
        $domain->setFromEmail($values['fromEmail']);
        $domain->setFromName($values['fromName']);
        $domain->setTimezone($values['timezone']);
        $domain->setSignature($values['signature']);
        if (!empty($values['address'])) {
            $domain->setAddress($values['address']);
        }
    }
}
