<?php

namespace Synduit\SynpostDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynpostDatabaseBundle\Document\DripMail;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DripMailRepository extends DocumentRepository
{
    public function createDripMail($values, $drip)
    {
        $drip_mail = new DripMail();
        $drip_mail->setDrip($drip);
        $this->prepareFields($drip_mail, $values);

        $dm = $this->getDocumentManager();
        $dm->persist($drip_mail);
        $drip->addDripMail($drip_mail);

        return $drip_mail;
    }

    /**
     * Set values to Documents.
     */
    private function prepareFields(&$drip_mail, $values)
    {
        $drip_mail->setSubject($values['subject']);
        $drip_mail->setBody($values['body']);
        $drip_mail->setInterval($values['interval']);
        $drip_mail->setTime($values['time']);
    }

    public function updateDripMail($drip_mail, $values)
    {
        $this->prepareFields($drip_mail, $values);
    }

    public function deleteDripMails($drip_mails)
    {
        foreach ($drip_mails as $drip_mail) {
            $drip_mail->setActive(false);
        }
    }
}
