<?php

namespace Synduit\SynpostDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynpostDatabaseBundle\Document\DripMailSchedule;

/**
 * DripMailScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DripMailScheduleRepository extends DocumentRepository
{
    public function createDripMailSchedule($values)
    {
        $dm = $this->getDocumentManager();
        foreach ($values as $value) {
            $drip_mail_schedule = new DripMailSchedule();
            $drip_mail_schedule->setDripMail($value['dripMail']);
            $drip_mail_schedule->setSubscriber($value['subscriber']);
            $drip_mail_schedule->setScheduleDate($value['scheduleDate']);
            $drip_mail_schedule->setCreated($value['created']);
            $dm->persist($drip_mail_schedule);
        }
    }

    public function findDripMailSchedulesForSending($last_cron_run, $current_date)
    {
        return $this->findBy(
            array(
                'scheduleDate' => array(
                    '$gte' => $last_cron_run,
                    '$lte' => $current_date,
                ),
                'sent' => false,
            )
        );
    }

    public function findDripMailScheduleBySubscriber($subscriber, $dripMail)
    {
        return $this->findOneBy(array(
            'subscriber' => $subscriber,
            'dripMail' => $dripMail,
        ));
    }
}
