<?php

namespace Synduit\SynpostDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynpostDatabaseBundle\Document\EmailBodyLink;

/**
 * EmailBodyLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailBodyLinkRepository extends DocumentRepository
{
    public function createEmailBodyLink($link, $subscriber, $options)
    {
        $email_body_link = new EmailBodyLink();
        $email_body_link->setActualLink($link);

        if (!empty($subscriber)) {
            $email_body_link->setSubscriber($subscriber);
        }
        if (isset($options['campaign'])) {
            $email_body_link->setCampaign($options['campaign']);
        }
        if (isset($options['dripMail'])) {
            $email_body_link->setDripMail($options['dripMail']);
        }

        $dm = $this->getDocumentManager();
        $dm->persist($email_body_link);
        $dm->flush();

        return $email_body_link;
    }
}
