<?php

namespace Synduit\SynpostDatabaseBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Synduit\SynpostDatabaseBundle\Document\Term;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends DocumentRepository
{
    public function createTerm($values, $category)
    {
        $term = new Term();
        $term->setName($values['name']);
        $term->setCategory($category);

        $dm = $this->getDocumentManager();
        $dm->persist($term);

        return $term;
    }

    public function findTermByCategoryAndName($category_id, $name)
    {
        return $this->findOneBy(
            array(
              'category' => $category_id,
              'name' => new \MongoRegex('/^' . $name . '$/i'),
            )
        );
    }

    public function findTermsByCategory($category_id, $parameters = array())
    {
        $query['category'] = $category_id;
        if (isset($parameters['visible'])) {
            $query['visible'] = $parameters['visible'];
        }
        return $this->findBy($query);
    }

    public function deleteTerms($terms)
    {
        $dm = $this->getDocumentManager();
        $subscriber_repo = $dm->getRepository('SynpostMailServiceBundle:Subscriber');
        foreach ($terms as $term) {
            $subscriber_repo->removeTermFromSubscribers($term);
            $dm->remove($term);
        }
    }

    public function hideTerms($terms)
    {
        foreach ($terms as $term) {
            $term->setVisible(FALSE);
        }
    }

    public function updateTerm($term, $values)
    {
        $term->setName($values['name']);
    }
}
